version: '2'

services:
  mariadb:
    image: bitnami/mariadb:10.1.25-r0
    environment:
      - MARIADB_ROOT_PASSWORD=rootpwd
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpresspwd
      - MARIADB_DATABASE=wordpressdb
    volumes:
      - ./mariadb-data:/bitnami/mariadb

  php-fpm:
    image: bitnami/php-fpm:5.6.31-r0
    depends_on:
      - mariadb
    volumes:
      - ./wordpress:/app

  apache:
    image: bitnami/apache:2.4.27-r0
    ports:
      - 80:80
    depends_on:
      - php-fpm
    volumes:
      - ./apache-vhost/wordpress.conf:/bitnami/apache/conf/vhosts/wordpress.conf:ro
      - ./wordpress:/app
